<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="Docker.DotNet" Version="3.125.15" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="2.1.341" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\ContainerPageView.axaml.cs">
        <DependentUpon>MainPageView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Control\ManuControl.axaml.cs">
        <DependentUpon>MenuControl.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Controls\ManuControlView.axaml.cs">
        <DependentUpon>MenuControlView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Pages\ImagePageView.axaml.cs">
        <DependentUpon>SettingPageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Pages\VolumePageView.axaml.cs">
        <DependentUpon>VolumePageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Controls\ModelViewerControlView.axaml.cs">
        <DependentUpon>DockerContainerInspectControlView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Controls\DialogControl\MessageDialogControl.axml.cs">
        <DependentUpon>MessageDialogControl.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
