using System.Collections.Generic;
using CommunityToolkit.Mvvm.ComponentModel;
using ScratchCube.ViewModels;

namespace ScratchCube.Models.Docker;

public partial class DockerHostConfig : ViewModelBase
{
    [ObservableProperty] private IList<string> _binds;
    [ObservableProperty] private string _containerIDFile;
    [ObservableProperty] private DockerLogConfig _logConfig;
    [ObservableProperty] private string _networkMode;
    [ObservableProperty] private IDictionary<string, IList<DockerPortBinding>> _portBindings;
    [ObservableProperty] private DockerRestartPolicy _restartPolicy;
    [ObservableProperty] private bool _autoRemove;
    [ObservableProperty] private string _volumeDriver;
    [ObservableProperty] private IList<string> _volumesFrom;
    [ObservableProperty] private IList<string> _capAdd;
    [ObservableProperty] private IList<string> _capDrop;
    [ObservableProperty] private string _cgroupnsMode;
    [ObservableProperty] private IList<string> _dns;
    [ObservableProperty] private IList<string> _dnsOptions;
    [ObservableProperty] private IList<string> _dnsSearch;
    [ObservableProperty] private IList<string> _extraHosts;
    [ObservableProperty] private IList<string> _groupAdd;
    [ObservableProperty] private string _ipcMode;
    [ObservableProperty] private string _cgroup;
    [ObservableProperty] private IList<string> _links;
    [ObservableProperty] private long _oomScoreAdj;
    [ObservableProperty] private string _pidMode;
    [ObservableProperty] private bool _privileged;
    [ObservableProperty] private bool _publishAllPorts;
    [ObservableProperty] private bool _readonlyRootfs;
    [ObservableProperty] private IList<string> _securityOpt;
    [ObservableProperty] private IDictionary<string, string> _storageOpt;
    [ObservableProperty] private IDictionary<string, string> _tmpfs;
    [ObservableProperty] private string _utsMode;
    [ObservableProperty] private string _usernsMode;
    [ObservableProperty] private long _shmSize;
    [ObservableProperty] private IDictionary<string, string> _sysctls;
    [ObservableProperty] private string _runtime;
    [ObservableProperty] private ulong[] _consoleSize;
    [ObservableProperty] private string _isolation;
    [ObservableProperty] private long _cpuShares;
    [ObservableProperty] private long _memory;
    [ObservableProperty] private long _nanoCPUs;
    [ObservableProperty] private string _cgroupParent;
    [ObservableProperty] private ushort _blkioWeight;
    [ObservableProperty] private IList<DockerThrottleDevice> _blkioDeviceReadBps;
    [ObservableProperty] private IList<DockerThrottleDevice> _blkioDeviceWriteBps;
    [ObservableProperty] private IList<DockerThrottleDevice> _blkioDeviceReadIOps;
    [ObservableProperty] private IList<DockerThrottleDevice> _blkioDeviceWriteIOps;
    [ObservableProperty] private long _cpuPeriod;
    [ObservableProperty] private long _cpuQuota;
    [ObservableProperty] private long _cpuRealtimePeriod;
    [ObservableProperty] private long _cpuRealtimeRuntime;
    [ObservableProperty] private string _cpusetCpus;
    [ObservableProperty] private string _cpusetMems;
    [ObservableProperty] private IList<DockerDeviceMapping> _devices;
    [ObservableProperty] private IList<string> _deviceCgroupRules;
    [ObservableProperty] private IList<DockerDeviceRequest> _deviceRequests;
    [ObservableProperty] private long _kernelMemory;
    [ObservableProperty] private long _kernelMemoryTCP;
    [ObservableProperty] private long _memoryReservation;
    [ObservableProperty] private long _memorySwap;
    [ObservableProperty] private long? _memorySwappiness;
    [ObservableProperty] private bool? _oomKillDisable;
    [ObservableProperty] private long? _pidsLimit;
    [ObservableProperty] private IList<DockerUlimit> _ulimits;
    [ObservableProperty] private long _cpuCount;
    [ObservableProperty] private long _cpuPercent;
    [ObservableProperty] private ulong _ioMaximumIOps;
    [ObservableProperty] private ulong _ioMaximumBandwidth;
    [ObservableProperty] private IList<DockerMount> _mounts;
    [ObservableProperty] private IList<string> _maskedPaths;
    [ObservableProperty] private IList<string> _readonlyPaths;
    [ObservableProperty] private bool? _init;
}